# Generated by Django 3.2.12 on 2023-11-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar_app', '0004_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('organ', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
