# Generated by Django 3.2.5 on 2023-12-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar_app', '0005_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
