# Generated by Django 3.2.5 on 2023-12-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar_app', '0006_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('contactno', models.IntegerField()),
                ('mail', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('emergency', models.IntegerField()),
                ('organtype', models.CharField(max_length=100)),
                ('agreement', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='organ',
        ),
    ]
