# Generated by Django 3.2.5 on 2023-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar_app', '0007_auto_20231207_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='password',
            new_name='address',
        ),
        migrations.AddField(
            model_name='recipient',
            name='disease',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
