# Generated by Django 4.2.5 on 2023-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar_app', '0008_auto_20231207_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_user',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
